"""initial

Revision ID: 0001
Revises:
Create Date: 2026-05-21 23:29:10.139364

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("license_number", sa.String(length=32), nullable=False),
        sa.Column("experience_years", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_number"),
    )
    op.create_table(
        "koap_articles",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("factor_group", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "score_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.String(length=16), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("safety_score", sa.Integer(), nullable=False),
        sa.Column("risk_tier", sa.String(length=16), nullable=False),
        sa.Column("premium_coef", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_score_snapshots_driver_id"), "score_snapshots", ["driver_id"], unique=False
    )
    op.create_table(
        "violations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.String(length=16), nullable=False),
        sa.Column("article_code", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.Date(), nullable=False),
        sa.Column("fine_kzt", sa.Integer(), nullable=True),
        sa.Column("at_fault", sa.Boolean(), nullable=True),
        sa.Column("recurrence_idx", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_code"],
            ["koap_articles.code"],
        ),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_violations_article_code"), "violations", ["article_code"], unique=False
    )
    op.create_index(op.f("ix_violations_driver_id"), "violations", ["driver_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_violations_driver_id"), table_name="violations")
    op.drop_index(op.f("ix_violations_article_code"), table_name="violations")
    op.drop_table("violations")
    op.drop_index(op.f("ix_score_snapshots_driver_id"), table_name="score_snapshots")
    op.drop_table("score_snapshots")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("koap_articles")
    op.drop_table("drivers")
    # ### end Alembic commands ###
